### ISSUE TITLE
Latest release no longer respects username field

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#51]
My pass entries look like this:

```
supersecretpassword
---
login:    pigmonkey
url:      https://somewhere.com
```

(Those are spaces separating the fields, not tabs.)

My `~/.config/rofi-pass/config` looks like this:

```
URL_field='url'
USERNAME_field='login'
clip=clipboard
notify='true'
```
After upgrading to rofi-pass v1.4, the autotype features types `<tab>supersecretpassword`. Using `alt+2` to copy the value of the login field does still work. If I edit my entry and rename `login` to `user`, autotype works.

The autotype function is not respecting `USERNAME_field`.

**Comment by pigmonkey** [comment]
Possibly related: when I use alt+2 to type the username, it actually prepends a single space to the username.

**Comment by carnager** [comment]
As for your 2nd comment: rofi-pass mimics yaml which only allows a single space after the colon. I merged a patch in the past that allowed for use of tabs, which had the side effect of allowing more than one space too. 

That said I now ignore leading whitespaces from field values. But you might want to consider to fix your password files, since this is not specs-compilant. I try to remain yaml compilant, since this makes rofi-pass compatible with autopass

**Comment by pigmonkey** [comment]
Autotype is working with my username field now.

I'm still getting the prefixed whitespace with my username. I agree that tabs are not YAML separators, but reading the spec I don't see where they specify that only a single space is allowed as a [separation character](http://yaml.org/spec/current.html#id2521201). They do say that [leading white space should be discarded](http://yaml.org/spec/current.html#id2521681).

**Comment by carnager** [comment]
can you try latest commit? 

I also have a strange issue, which doesnt affect day to day work, but its still odd.
When hitting Enter on an entry and default_do is "autopass" I get an error on terminal about some of the fieldnames not being a valid command. if i use Alt+t and hit autotype there, I don't get that error. Both ways call exactly the same command...

**Comment by pigmonkey** [comment]
The latest commit works great! No more leading whitespace in my username.

With `default_do` set to `autopass`, if I run the latest `rofi-pass` from the terminal and select an entry, it outputs:

```
autopass
usertab<tab>password
```

On line 330 you're echoing `default_do`, which causes the first line of output. I'm not sure if there is a reason for that (maybe just a debug echo?), but that could be the cause of your issue. Your terminal is saying that `autopass` is not a valid command.

**Comment by carnager** [comment]
so you are not getting what i am getting, how bizarre...

```
autopass
1051027173_c	Den6j./rofi-pass: line 350: user: command not found
```

**Comment by pigmonkey** [comment]
Nope, I don't get that. I use ZSH, if it matters.

**Comment by carnager** [comment]
Ok, it strangely works when using "autotype" as default_do. Using "autopass" it gives the above error. I am lost here :)
